# -*- coding: utf-8 -*-
"""Full-database review pass for the Russian translation of Sword of Convallaria.

Covers EVERY TM entry (not only gendered dialogue): semantic accuracy,
mistranslations (e.g. "Follow me" -> "следуй за мной", NOT "следи за мной"),
gender agreement, typos, style consistency with the glossary.

Phases:
  queue  — build review_queue.jsonl (all TM entries + speaker/gender context)
  run    — LLM review -> review_done.jsonl (resumable, parallel workers)
  apply  — validate tags, update TM in place (tm/tm_ru.json)

Context files (optional, improve quality):
  review_context.txt — glossary + named character genders + lore notes,
  generated by build_review_context.py after web research.
"""
import json, os, re, sys, time, hashlib, urllib.request, collections, threading

BASE = os.path.dirname(os.path.abspath(__file__))
API_URL = 'https://router.requesty.ai/v1/chat/completions'
API_KEY = os.environ.get('REQUESTY_API_KEY', '')
MODEL = os.environ.get('REVIEW_MODEL', 'sference/deepseek-v4-flash-0731')
FALLBACK_MODEL = 'deepseek/deepseek-v4-flash'
QUEUE = os.path.join(BASE, 'review_queue.jsonl')
DONE = os.path.join(BASE, 'review_done.jsonl')
TM_PATH = os.path.join(BASE, 'tm/tm_ru.json')
CTX_PATH = os.path.join(BASE, 'review_context.txt')
WORKERS = int(os.environ.get('REVIEW_WORKERS', '8'))
BATCH = int(os.environ.get('REVIEW_BATCH', '50'))

TAG_RE = re.compile(r'<[^>]+>|\{\w*\}|%[\d.]*[sdif]|\\n|\[\w+\]')


def key_of(s):
    return hashlib.sha1(s.encode('utf-8')).hexdigest()[:16]


def tags_of(s):
    return TAG_RE.findall(s)


# ---------------------------------------------------------------- queue
def build_queue():
    tm = json.load(open(TM_PATH, encoding='utf-8'))
    spk_map = json.load(open(os.path.join(BASE, 'speaker_map.json'), encoding='utf-8'))
    genders = json.load(open(os.path.join(BASE, 'speakers_gender.json'), encoding='utf-8'))
    tr_path = os.path.join(BASE, 'out/dblang_en/translation.json')
    en2spk = collections.defaultdict(collections.Counter)
    if os.path.exists(tr_path):
        tr = json.load(open(tr_path, encoding='utf-8'))
        en_by_id = {str(int(e[0])): e[2] for e in tr}
        for lid, speaker in spk_map.items():
            en = en_by_id.get(lid)
            if en:
                en2spk[en][(speaker, genders.get(speaker, 'unknown'))] += 1
    n_spk = 0
    with open(QUEUE, 'w', encoding='utf-8') as f:
        for k, t in tm.items():
            item = {'k': k, 'en': t['en'], 'ru': t['ru']}
            spk = en2spk.get(t['en'])
            if spk:
                gs = set(g for (_, g), _ in spk.items())
                if len(gs) == 1:
                    (speaker, g), _ = spk.most_common(1)[0]
                    item['speaker'], item['g'] = speaker, g
                else:
                    item['speaker'] = '/'.join(s for (s, _), _ in spk.most_common(3))
                    item['g'] = 'multi'
                n_spk += 1
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
    print('queued:', len(tm), 'with speaker ctx:', n_spk)


# ---------------------------------------------------------------- run
def load_prompt():
    ctx = ''
    if os.path.exists(CTX_PATH):
        ctx = open(CTX_PATH, encoding='utf-8').read()
    return '''You are proofreading a Russian fan translation of the tactical RPG
"Sword of Convallaria" (EN -> RU). Each item is one string from the game:
"en" = source, "ru" = current translation. Some items include "speaker"
(who says the line) and "g" (their gender: m/f; "multi" = several speakers
of different genders share this EN text; "neutral" = the player character —
must stay genderless; "variable" = generic NPC whose gender varies).

Your job — find and fix REAL problems only:
1. Mistranslation / wrong meaning (classic case: "Follow me" must be
   "Следуй за мной", NOT "Следи за мной"; "watch" vs "follow" etc.).
2. Wrong gender agreement for the speaker (past-tense -л/-ла, short
   adjectives рад/рада, готов/готова...). For "multi" lines prefer forms
   that work for any gender or keep current if already neutral.
3. Typos, broken Russian grammar, wrong punctuation.
4. Terminology inconsistent with the glossary below.
5. Untranslated English left in "ru" (except proper names per glossary).

Do NOT:
- rephrase correct translations (style is already good; respect it);
- change meaning, add or drop content, change length drastically;
- touch markup: preserve <...>, {0}, %s, \\n, [Keyword] EXACTLY, same order;
- translate or alter proper names fixed by the glossary.

Reply with ONLY a JSON array, one object per input item, same order:
[{"k": "<key>", "ru": "<final russian>", "changed": true|false}, ...]
Use "changed": false + the original "ru" when the line is fine.

''' + ctx + '''
ITEMS:
'''


_lock = threading.Lock()


def run(limit=0):
    queue = [json.loads(l) for l in open(QUEUE, encoding='utf-8')]
    done = set()
    if os.path.exists(DONE):
        for l in open(DONE, encoding='utf-8'):
            done.add(json.loads(l)['k'])
    todo = [q for q in queue if q['k'] not in done]
    if limit:
        todo = todo[:limit]
    print('todo:', len(todo), 'done:', len(done), 'model:', MODEL, flush=True)
    prompt = load_prompt()
    batches = [todo[i:i + BATCH] for i in range(0, len(todo), BATCH)]
    fout = open(DONE, 'a', encoding='utf-8')
    stats = {'batches': 0, 'failed': 0}

    def work(batch):
        items = '\n'.join(json.dumps(q, ensure_ascii=False) for q in batch)
        body = json.dumps({'model': MODEL,
                           'messages': [{'role': 'user', 'content': prompt + items}],
                           'temperature': 0.0, 'max_tokens': 16000,
                           'reasoning_effort': 'low'}).encode()
        res = None
        model = MODEL
        for attempt in range(6):
            try:
                req = urllib.request.Request(API_URL, data=body, headers={
                    'Authorization': 'Bearer ' + API_KEY,
                    'Content-Type': 'application/json'})
                r = json.load(urllib.request.urlopen(req, timeout=600))
                txt = r['choices'][0]['message']['content']
                m = re.search(r'\[.*\]', txt, re.S)
                res = json.loads(m.group(0))
                break
            except Exception as e:
                msg = str(e)[:150]
                print('retry %d: %s' % (attempt, msg), flush=True)
                if attempt == 0 and ('403' in msg or 'model' in msg.lower()):
                    model = FALLBACK_MODEL  # one-shot fallback
                    body = json.dumps({'model': model,
                                       'messages': [{'role': 'user', 'content': prompt + items}],
                                       'temperature': 0.0, 'max_tokens': 16000,
                                       'reasoning_effort': 'low'}).encode()
                time.sleep(5 + 10 * attempt)
        with _lock:
            if res is None:
                stats['failed'] += 1
                print('batch FAILED (%d items), will retry on next run' % len(batch), flush=True)
                return
            by_k = {x.get('k'): x for x in res if isinstance(x, dict)}
            for q in batch:
                x = by_k.get(q['k'])
                if not x or not isinstance(x.get('ru'), str):
                    x = {'k': q['k'], 'ru': q['ru'], 'changed': False, 'missing': True}
                x['en'] = q['en']
                x['ru_old'] = q['ru']
                fout.write(json.dumps(x, ensure_ascii=False) + '\n')
            fout.flush()
            stats['batches'] += 1
            if stats['batches'] % 20 == 0:
                print('batches done:', stats['batches'], '/', len(batches), flush=True)

    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        list(ex.map(work, batches))
    fout.close()
    print('finished. batches:', stats['batches'], 'failed:', stats['failed'])


# ---------------------------------------------------------------- apply
def apply():
    tm = json.load(open(TM_PATH, encoding='utf-8'))
    n_changed = n_tag_bad = n_stale = n_empty = 0
    seen = set()
    for l in open(DONE, encoding='utf-8'):
        x = json.loads(l)
        if not x.get('changed') or x['k'] in seen:
            continue
        seen.add(x['k'])
        k = x['k']
        if k not in tm or tm[k]['ru'] != x['ru_old']:
            n_stale += 1
            continue
        if not x['ru'].strip():
            n_empty += 1
            continue
        if tags_of(x['ru']) != tags_of(x['ru_old']):
            n_tag_bad += 1
            continue
        tm[k]['ru'] = x['ru']
        n_changed += 1
    json.dump(tm, open(TM_PATH, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print('applied:', n_changed, '| tag-rejected:', n_tag_bad,
          '| stale:', n_stale, '| empty:', n_empty)


if __name__ == '__main__':
    cmd = sys.argv[1]
    if cmd == 'queue':
        build_queue()
    elif cmd == 'run':
        run(limit=int(sys.argv[2]) if len(sys.argv) > 2 else 0)
    elif cmd == 'apply':
        apply()
